# -*- coding: utf-8 -*-
"""
/***************************************************************************
 simex_plugin
                                 A QGIS plugin
 O Plugin SIMEX é uma ferramenta que utiliza imagens de satélite (Landsat e Sentinel 2) integrada à base de dados geoespaciais para o monitoramento de áreas de atividade madeireira. As informações extraídas das imagens contribuem no licenciamento e monitoramento de Planos de Manejo Florestal, além de facilitar na identificação de áreas de exploração não autorizadas. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-19
        copyright            : (C) 2021 by Diego SIlva - Consultor SIG 
        email                : dii.manut@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load simex_plugin class from file simex_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .simex_plugin import simex_plugin
    return simex_plugin(iface)
